# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

InstitutionCategory.delete_all
InstitutionCategory.create(:name => "University", :abbreviation => "uni")
InstitutionCategory.create(:name => "Third Level College", :abbreviation => "tlc")
InstitutionCategory.create(:name => "Institute of Technology", :abbreviation => "iot")
InstitutionCategory.create(:name => "Vocational Education Committee", :abbreviation => "vec")
InstitutionCategory.create(:name => "Other", :abbreviation => "oo")

Institution.delete_all
Institution.create(:name => "Dublin City University", :category_id => InstitutionCategory.find_by_abbreviation("uni").id)
Institution.create(:name => "NUI Galway", :category_id => InstitutionCategory.find_by_abbreviation("uni").id)
Institution.create(:name => "NUI Maynooth", :category_id => InstitutionCategory.find_by_abbreviation("uni").id)
Institution.create(:name => "Trinity College Dublin", :category_id => InstitutionCategory.find_by_abbreviation("uni").id)
Institution.create(:name => "University College Cork", :category_id => InstitutionCategory.find_by_abbreviation("uni").id)
Institution.create(:name => "University College Dublin", :category_id => InstitutionCategory.find_by_abbreviation("uni").id)
Institution.create(:name => "University of Limerick", :category_id => InstitutionCategory.find_by_abbreviation("uni").id)
Institution.create(:name => "Carlow College", :category_id => InstitutionCategory.find_by_abbreviation("tlc").id)
Institution.create(:name => "College of Anaesthetists of Ireland", :category_id => InstitutionCategory.find_by_abbreviation("tlc").id)
Institution.create(:name => "National College of Art and Design", :category_id => InstitutionCategory.find_by_abbreviation("tlc").id)
Institution.create(:name => "National College of Ireland (formerly NCIR)", :category_id => InstitutionCategory.find_by_abbreviation("tlc").id)
Institution.create(:name => "Royal College of Physicians of Ireland", :category_id => InstitutionCategory.find_by_abbreviation("tlc").id)
Institution.create(:name => "Royal College of Surgeons in Ireland", :category_id => InstitutionCategory.find_by_abbreviation("tlc").id)
Institution.create(:name => "St. Patricks College, Thurles, Co. Tipperary", :category_id => InstitutionCategory.find_by_abbreviation("tlc").id)
Institution.create(:name => "Athlone IT", :category_id => InstitutionCategory.find_by_abbreviation("iot").id)
Institution.create(:name => "Cork IT", :category_id => InstitutionCategory.find_by_abbreviation("iot").id)
Institution.create(:name => "DIT", :category_id => InstitutionCategory.find_by_abbreviation("iot").id)
Institution.create(:name => "Dundalk IT", :category_id => InstitutionCategory.find_by_abbreviation("iot").id)
Institution.create(:name => "Galway-Mayo IT", :category_id => InstitutionCategory.find_by_abbreviation("iot").id)
Institution.create(:name => "Institute of Art, Design and Technology, Dun Laoghaire", :category_id => InstitutionCategory.find_by_abbreviation("iot").id)
Institution.create(:name => "Institutes of Technology Ireland", :category_id => InstitutionCategory.find_by_abbreviation("iot").id)
Institution.create(:name => "IT Blanchardstown", :category_id => InstitutionCategory.find_by_abbreviation("iot").id)
Institution.create(:name => "IT Carlow", :category_id => InstitutionCategory.find_by_abbreviation("iot").id)
Institution.create(:name => "IT Sligo", :category_id => InstitutionCategory.find_by_abbreviation("iot").id)
Institution.create(:name => "IT Tallaght", :category_id => InstitutionCategory.find_by_abbreviation("iot").id)
Institution.create(:name => "IT Tralee", :category_id => InstitutionCategory.find_by_abbreviation("iot").id)
Institution.create(:name => "Letterkenny IT", :category_id => InstitutionCategory.find_by_abbreviation("iot").id)
Institution.create(:name => "Limerick IT", :category_id => InstitutionCategory.find_by_abbreviation("iot").id)
Institution.create(:name => "Waterford IT", :category_id => InstitutionCategory.find_by_abbreviation("iot").id)
Institution.create(:name => "Cavan VEC", :category_id => InstitutionCategory.find_by_abbreviation("vec").id)
Institution.create(:name => "Cork VEC - Administrative Office", :category_id => InstitutionCategory.find_by_abbreviation("vec").id)
Institution.create(:name => "City of Dublin VEC", :category_id => InstitutionCategory.find_by_abbreviation("vec").id)
Institution.create(:name => "City of Limerick VEC", :category_id => InstitutionCategory.find_by_abbreviation("vec").id)
Institution.create(:name => "Colaiste Stiofain Naofa", :category_id => InstitutionCategory.find_by_abbreviation("vec").id)
Institution.create(:name => "Kildare VEC", :category_id => InstitutionCategory.find_by_abbreviation("vec").id)
Institution.create(:name => "Meath VEC", :category_id => InstitutionCategory.find_by_abbreviation("vec").id)
Institution.create(:name => "Offaly VEC", :category_id => InstitutionCategory.find_by_abbreviation("vec").id)
Institution.create(:name => "St John's Central College", :category_id => InstitutionCategory.find_by_abbreviation("vec").id)
Institution.create(:name => "An Cheim", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "Central Applications Office (CAO)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "Dublin Institute for Advanced Studies (DIAS)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "Environmental Protection Agency (EPA)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "Economic and Social Research Institute (ESRI)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "Further Education and Training Awards Council (FETAC)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "Grangegorman Development Agency (GDA)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "Georgia Tech Ireland (GTI)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "Health Research Board (HRB)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "Higher Education Authority (HEA)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "Hermes (NCTE)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "Higher Education and Training Awards Council (HETAC)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "ICHEC", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "IE Domain Registry (IEDR)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "Institute of Public Administration (IPA)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "Irish Universities Association (IUA)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "IVEA", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "Marine Institute", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "National Cancer Registry, Ireland (NCRI)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "National Centre for Technology in Education (NCTE)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "National University of Ireland (NUI)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "National Digital Research Centre (NDRC)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "National Qualifications Authority of Ireland (NQAI)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "Post-Graduate Applications Centre (PAC)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)
Institution.create(:name => "Royal Irish Academy (RIA)", :category_id => InstitutionCategory.find_by_abbreviation("oo").id)

InstitutionAbbreviation.delete_all
InstitutionAbbreviation.create(:abbreviation => "") 
InstitutionAbbreviation.create(:abbreviation => "-1") 
InstitutionAbbreviation.create(:abbreviation => "AD") 
InstitutionAbbreviation.create(:abbreviation => "AL") 
InstitutionAbbreviation.create(:abbreviation => "AS") 
InstitutionAbbreviation.create(:abbreviation => "BCFE") 
InstitutionAbbreviation.create(:abbreviation => "BN") 
InstitutionAbbreviation.create(:abbreviation => "CDVEC") 
InstitutionAbbreviation.create(:abbreviation => "CHEIM")
InstitutionAbbreviation.create(:abbreviation => "CK") 
InstitutionAbbreviation.create(:abbreviation => "CR") 
InstitutionAbbreviation.create(:abbreviation => "CSN") 
InstitutionAbbreviation.create(:abbreviation => "CVEC") 
InstitutionAbbreviation.create(:abbreviation => "CW") 
InstitutionAbbreviation.create(:abbreviation => "DC") 
InstitutionAbbreviation.create(:abbreviation => "DK") 
InstitutionAbbreviation.create(:abbreviation => "DL") 
InstitutionAbbreviation.create(:abbreviation => "DN") 
InstitutionAbbreviation.create(:abbreviation => "DIAS") 
InstitutionAbbreviation.create(:abbreviation => "dit") 
InstitutionAbbreviation.create(:abbreviation => "DKIT") 
InstitutionAbbreviation.create(:abbreviation => "DT") 
InstitutionAbbreviation.create(:abbreviation => "EPA") 
InstitutionAbbreviation.create(:abbreviation => "FETAC") 
InstitutionAbbreviation.create(:abbreviation => "GA") 
InstitutionAbbreviation.create(:abbreviation => "GY") 
InstitutionAbbreviation.create(:abbreviation => "HEA") 
InstitutionAbbreviation.create(:abbreviation => "HEANET") 
InstitutionAbbreviation.create(:abbreviation => "HETAC") 
InstitutionAbbreviation.create(:abbreviation => "HRB") 
InstitutionAbbreviation.create(:abbreviation => "IAS") 
InstitutionAbbreviation.create(:abbreviation => "IOTI")
InstitutionAbbreviation.create(:abbreviation => "IPA") 
InstitutionAbbreviation.create(:abbreviation => "LC") 
InstitutionAbbreviation.create(:abbreviation => "LIT") 
InstitutionAbbreviation.create(:abbreviation => "LM") 
InstitutionAbbreviation.create(:abbreviation => "LY") 
InstitutionAbbreviation.create(:abbreviation => "MARINE") 
InstitutionAbbreviation.create(:abbreviation => "MH") 
InstitutionAbbreviation.create(:abbreviation => "NC") 
InstitutionAbbreviation.create(:abbreviation => "NUI") 
InstitutionAbbreviation.create(:abbreviation => "PCC") 
InstitutionAbbreviation.create(:abbreviation => "RC") 
InstitutionAbbreviation.create(:abbreviation => "RIA") 
InstitutionAbbreviation.create(:abbreviation => "SG") 
InstitutionAbbreviation.create(:abbreviation => "SJCC") 
InstitutionAbbreviation.create(:abbreviation => "TA")
InstitutionAbbreviation.create(:abbreviation => "TCD") 
InstitutionAbbreviation.create(:abbreviation => "TI") 
InstitutionAbbreviation.create(:abbreviation => "TL") 
InstitutionAbbreviation.create(:abbreviation => "TR") 
InstitutionAbbreviation.create(:abbreviation => "WD") 
InstitutionAbbreviation.create(:abbreviation => "WIT")

MbbChannel.delete_all
MbbChannel.create(:name => "Retail")
MbbChannel.create(:name => "Campus")
MbbChannel.create(:name => "Franchise")
MbbChannel.create(:name => "Online")
MbbChannel.create(:name => "CPW")

MbbProduct.delete_all
MbbProduct.create(:name => "Prepay Voice Data Add On")
MbbProduct.create(:name => "Postpay Voice Data Add On")
MbbProduct.create(:name => "Postpay MBB")
MbbProduct.create(:name => "#N/A")
MbbProduct.create(:name => "Prepay MBB")

MbbSeason.delete_all
MbbSeason.create(:season_begin => "2008-09-01", season_end: "2009-08-31")
MbbSeason.create(:season_begin => "2009-09-01", season_end: "2010-08-31")
MbbSeason.create(:season_begin => "2010-09-01", season_end: "2011-08-31")
MbbSeason.create(:season_begin => "2011-09-01", season_end: "2012-08-31")
